import type { Exercise, MuscleGroup } from "@/types";

export const DEFAULT_DISHES = [
  "Bruschetta",
  "Caesar Salad",
  "Garlic Bread",
  "Chicken Wings",
  "Spring Rolls",
  "Soup of the Day",
  "Grilled Salmon",
  "Ribeye Steak",
  "Chicken Parmesan",
  "Mushroom Risotto",
  "Beef Burger",
  "Pasta Carbonara",
  "Fish and Chips",
  "BBQ Ribs",
  "Margherita Pizza",
  "French Fries",
  "Mashed Potatoes",
  "Steamed Vegetables",
  "Onion Rings",
  "Mac and Cheese",
  "Side Salad",
  "Chocolate Cake",
  "Cheesecake",
  "Tiramisu",
  "Crème Brûlée",
  "Ice Cream Sundae",
  "House Wine",
  "Craft Beer",
  "Sparkling Water",
  "Fresh Juice",
  "Espresso",
  "Chef's Special",
  "Daily Special",
  "Seasonal Plate",
  "Eggs Benedict",
  "Avocado Toast",
  "French Toast",
  "Granola Bowl",
  "Cheese Board",
  "Bread Basket",
] as const;

const CATEGORY_BY_NAME: Record<(typeof DEFAULT_DISHES)[number], MuscleGroup> = {
  "Bruschetta": "starters",
  "Caesar Salad": "starters",
  "Garlic Bread": "starters",
  "Chicken Wings": "starters",
  "Spring Rolls": "starters",
  "Soup of the Day": "starters",
  "Grilled Salmon": "mains",
  "Ribeye Steak": "mains",
  "Chicken Parmesan": "mains",
  "Mushroom Risotto": "mains",
  "Beef Burger": "mains",
  "Pasta Carbonara": "mains",
  "Fish and Chips": "mains",
  "BBQ Ribs": "mains",
  "Margherita Pizza": "mains",
  "French Fries": "sides",
  "Mashed Potatoes": "sides",
  "Steamed Vegetables": "sides",
  "Onion Rings": "sides",
  "Mac and Cheese": "sides",
  "Side Salad": "sides",
  "Chocolate Cake": "desserts",
  "Cheesecake": "desserts",
  "Tiramisu": "desserts",
  "Crème Brûlée": "desserts",
  "Ice Cream Sundae": "desserts",
  "House Wine": "drinks",
  "Craft Beer": "drinks",
  "Sparkling Water": "drinks",
  "Fresh Juice": "drinks",
  "Espresso": "drinks",
  "Chef's Special": "specials",
  "Daily Special": "specials",
  "Seasonal Plate": "specials",
  "Eggs Benedict": "breakfast",
  "Avocado Toast": "breakfast",
  "French Toast": "breakfast",
  "Granola Bowl": "breakfast",
  "Cheese Board": "snacks",
  "Bread Basket": "snacks",
};

const slugify = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-");

export const SEED_EXERCISES: Exercise[] = DEFAULT_DISHES.map((name) => ({
  id: slugify(name),
  name,
  muscleGroup: CATEGORY_BY_NAME[name],
}));
